using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace PalDDD.Core.SourceGen;


// ─────────────────────────────────────────────────────────────
// 源码生成器 — 智能枚举
// ─────────────────────────────────────────────────────────────

/// <summary>智能枚举增量源码生成器 — 编译时 walk 语法树，产出硬编码字段引用，完全 AOT 兼容</summary>
/// <remarks>
/// 生成代码通过调用 <c>RegisterValues([Field1, Field2, ...])</c> 在静态构造函数中注入编译时已知的值。<br/>
/// 运行时零反射——所有字段名在编译时已确定。<br/>
/// 用法：<c>[PalGenerateEnum] public partial class OrderStatus : SmartEnum&lt;OrderStatus, string&gt; { ... }</c>
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class EnumGenerator : IIncrementalGenerator
{
    private const string AttrName = "PalDDD.Core.GenerateEnumAttribute";

    private static readonly DiagnosticDescriptor NoFieldsWarning = new(
        "PALENUM001",
        "Generated enum has no static fields to register",
        "Type '{0}' is marked with [GenerateEnum] but has no public static readonly fields. Add at least one field or remove the attribute.",
        "PalDDD.EnumGeneration",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 步骤 1：收集所有标记了 [PalGenerateEnum] 的 partial class 及其静态字段
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttrName,
            predicate: static (node, _) =>
                node is ClassDeclarationSyntax c
                && c.Modifiers.Any(SyntaxKind.PartialKeyword),
            transform: static (context, ct) =>
            {
                var classSymbol = (INamedTypeSymbol)context.TargetSymbol;
                var classDecl = (ClassDeclarationSyntax)context.TargetNode;

                // 从基类 SmartEnum<TSelf, TValue> 提取 TValue
                var baseType = classSymbol.BaseType;
                if (baseType is not INamedTypeSymbol { TypeArguments.Length: 2 } namedBase)
                    return null;

                var valueType = namedBase.TypeArguments[1];

                // 编译时 walk 语法树：收集所有 public static readonly 字段名
                var fields = ImmutableArray.CreateBuilder<string>();
                foreach (var member in classDecl.Members)
                {
                    if (member is FieldDeclarationSyntax fds
                        && fds.Modifiers.Any(SyntaxKind.StaticKeyword)
                        && (fds.Modifiers.Any(SyntaxKind.PublicKeyword) || fds.Modifiers.Any(SyntaxKind.InternalKeyword)))
                    {
                        foreach (var variable in fds.Declaration.Variables)
                            fields.Add(variable.Identifier.Text);
                    }
                }

                if (fields.Count == 0)
                {
                    // 有 [GenerateEnum] 但无静态字段 — 返回空字段信息以触发警告
                    return new EnumGenInfo(
                        Namespace: classSymbol.ContainingNamespace?.ToDisplayString() ?? "_",
                        TypeName: classSymbol.Name,
                        ValueType: valueType.ToDisplayString(),
                        Fields: [],
                        HasFields: false);
                }

                return new EnumGenInfo(
                    Namespace: classSymbol.ContainingNamespace?.ToDisplayString() ?? "_",
                    TypeName: classSymbol.Name,
                    ValueType: valueType.ToDisplayString(),
                    Fields: fields.ToImmutable(),
                    HasFields: true);
            })
            .WithTrackingName("EnumGenerator_Candidates")
            .Where(static info => info is not null)!;

        // 步骤 2：有字段时生成，无字段时报告警告
        context.RegisterSourceOutput(candidates, static (spc, info) =>
        {
            if (!info!.HasFields)
            {
                // 报告警告而非静默跳过
                spc.ReportDiagnostic(Diagnostic.Create(
                    NoFieldsWarning,
                    Location.None,
                    info.TypeName));
                return;
            }
            spc.AddSource(
                $"{info!.Namespace}.{info.TypeName}.g.cs",
                GenerateEnumCode(info));
        });
    }

    /// <summary>生成硬编码字段引用的静态构造函数——零反射，100% AOT 兼容</summary>
    private static string GenerateEnumCode(EnumGenInfo info)
    {
        // 构建字段列表：Field1, Field2, Field3
        var fieldList = string.Join(",\n            ", info.Fields);

        return $$"""
// <auto-generated/>
using System.Runtime.CompilerServices;

namespace {{info.Namespace}};

partial class {{info.TypeName}}
{
    /// <summary>编译时值注册——所有字段引用均为硬编码，零反射，完全 AOT 兼容</summary>
    [ModuleInitializer]
    internal static void __PalRegisterValues()
    {
        RegisterValues([
            {{fieldList}}
        ]);
    }
}
""";
    }

    private sealed record EnumGenInfo(
        string Namespace,
        string TypeName,
        string ValueType,
        ImmutableArray<string> Fields,
        bool HasFields = true);
}
