using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace PalDDD.Core.SourceGen;


// ─────────────────────────────────────────────────────────────
// 源码生成器 — 强类型 ID
// ─────────────────────────────────────────────────────────────

[Generator(LanguageNames.CSharp)]
public sealed class IdentityGenerator : IIncrementalGenerator
{
    private const string AttributeName = "PalDDD.Core.GenerateIdAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeName,
            predicate: static (node, _) => IsPartialStruct(node),
            transform: static (context, ct) =>
            {
                var structSymbol = (INamedTypeSymbol)context.TargetSymbol;
                var attrData = context.Attributes[0];
                var sourceType = (INamedTypeSymbol)attrData.ConstructorArguments[0].Value!;

                return new IdGenInfo(
                    structSymbol.ContainingNamespace?.ToDisplayString() ?? "_",
                    structSymbol.Name,
                    sourceType.ToDisplayString() switch
                    {
                        "System.Guid" => "Guid",
                        "int" => "int",
                        "long" => "long",
                        "string" => "string",
                        "ByteAether.Ulid" => "Ulid",
                        _ => sourceType.Name
                    },
                    sourceType.Name is "Int32" or "Int64" && sourceType.ContainingNamespace?.ToDisplayString() == "System");
            })
            .WithTrackingName("IdentityGenerator_Candidates")
            .Where(static info => info is not null)!;

        context.RegisterSourceOutput(candidates, static (spc, info) =>
        {
            var src = GenerateIdentityCode(info);
            spc.AddSource($"{info.Namespace}.{info.TypeName}.g.cs", src);
        });
    }

    private static bool IsPartialStruct(SyntaxNode node)
        => node switch
        {
            StructDeclarationSyntax s => s.Modifiers.Any(SyntaxKind.PartialKeyword),
            RecordDeclarationSyntax r => r.ClassOrStructKeyword.IsKind(SyntaxKind.StructKeyword)
                                         && r.Modifiers.Any(SyntaxKind.PartialKeyword),
            _ => false
        };

    private static string GenerateIdentityCode(IdGenInfo info)
    {
        var ns = info.Namespace;
        var name = info.TypeName;
        var srcType = info.SourceType;

        var ulidUsing = srcType == "Ulid" ? "\r\nusing PalUlid = ByteAether.Ulid.Ulid;" : "";

        return $$"""
// <auto-generated/>
#nullable enable
using System;
		using System.ComponentModel;
		using System.Globalization;
		using System.Text.Json;
		using System.Text.Json.Serialization;
		using PalDDD.Core;{{ulidUsing}}

namespace {{ns}};

[TypeConverter(typeof({{name}}TypeConverter))]
[JsonConverter(typeof({{name}}JsonConverter))]
public readonly partial record struct {{name}} : IPalIdentity<{{srcType}}>, ISpanParsable<{{name}}>
{
    public {{srcType}} Value { get; init; }

    public static {{name}} New() => {{NewBody(srcType)}};
    public static {{name}} From({{srcType}} value) => {{FromBody(srcType)}};
    public override string ToString() => Value.ToString()!;
    public static bool TryParse(string? input, out {{name}} result)
    {
{{TryParseBody(srcType)}}
    }

    // ── ISpanParsable<T> 实现（AOT 安全，ASP.NET Core Minimal API 绑定兼容）──

    public static {{name}} Parse(string s, IFormatProvider? provider)
        => TryParse(s, out var r) ? r : throw new FormatException("Cannot parse '" + s + "' as " + typeof({{name}}).Name + ".");

    public static bool TryParse(string? s, IFormatProvider? provider, out {{name}} result)
        => TryParse(s, out result);

    public static {{name}} Parse(ReadOnlySpan<char> s, IFormatProvider? provider)
        => TryParse(s, provider, out var r) ? r : throw new FormatException("Cannot parse '" + s.ToString() + "' as " + typeof({{name}}).Name + ".");

    public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out {{name}} result)
    {
{{TryParseSpanBody(srcType)}}
    }
{{(info.IsNumeric ? NumericOperators(name, srcType) : "")}}
}

internal sealed class {{name}}JsonConverter : JsonConverter<{{name}}>
{
    public override {{name}} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
{{JsonReadBody(srcType, name)}}
    }

    public override void Write(Utf8JsonWriter writer, {{name}} value, JsonSerializerOptions options)
    {
{{JsonWriteBody(srcType)}}
    }
}

internal sealed class {{name}}TypeConverter : TypeConverter
{
    public override bool CanConvertFrom(ITypeDescriptorContext? context, Type sourceType)
        => sourceType == typeof(string) || sourceType == typeof({{srcType}});

    public override object? ConvertFrom(ITypeDescriptorContext? context, CultureInfo? culture, object value)
        => value switch
        {
            string s when {{name}}.TryParse(s, out var parsed) => parsed,
            {{srcType}} v => {{name}}.From(v),
            _ => throw new NotSupportedException()
        };
}
""";
    }

    private static string NewBody(string srcType) => srcType switch
    {
        "Guid" => "new() { Value = Guid.NewGuid() }",
        "Ulid" => "new() { Value = PalUlid.New() }",
        // 数值/字符串类型 Id 由数据库或服务端分配，客户端 New() 无意义 —— 明确报错而非静默返回 default。
        _ => "throw new NotSupportedException(\"Numeric/string identities are assigned by the store; use From(value) instead.\")"
    };

    private static string FromBody(string srcType) => srcType switch
    {
        "string" => "!string.IsNullOrEmpty(value) ? new() { Value = value } : throw new ArgumentException(\"String identity value cannot be null or empty.\", nameof(value))",
        _ => "new() { Value = value }"
    };

    private static string TryParseBody(string srcType) => srcType switch
    {
        "Guid" => "        if (Guid.TryParse(input, out var v)) { result = new() { Value = v }; return true; } result = default; return false;",
        "Ulid" => "        if (PalUlid.TryParse(input, CultureInfo.InvariantCulture, out var v)) { result = new() { Value = v }; return true; } result = default; return false;",
        "int" => "        if (int.TryParse(input, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v)) { result = new() { Value = v }; return true; } result = default; return false;",
        "long" => "        if (long.TryParse(input, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v)) { result = new() { Value = v }; return true; } result = default; return false;",
        "string" => "        if (!string.IsNullOrEmpty(input)) { result = new() { Value = input }; return true; } result = default; return false;",
        _ => "        result = default; return false;"
    };

    private static string TryParseSpanBody(string srcType) => srcType switch
    {
        "Guid" => "        if (Guid.TryParse(s, out var v)) { result = new() { Value = v }; return true; } result = default; return false;",
        "Ulid" => "        if (PalUlid.TryParse(s, CultureInfo.InvariantCulture, out var v)) { result = new() { Value = v }; return true; } result = default; return false;",
        "int" => "        if (int.TryParse(s, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v)) { result = new() { Value = v }; return true; } result = default; return false;",
        "long" => "        if (long.TryParse(s, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v)) { result = new() { Value = v }; return true; } result = default; return false;",
        "string" => "        if (!s.IsEmpty) { result = new() { Value = s.ToString() }; return true; } result = default; return false;",
        _ => "        result = default; return false;"
    };

    private static string JsonReadBody(string srcType, string name) => srcType switch
    {
        "Guid" => $"        return {name}.From(reader.GetGuid());",
        "Ulid" => $"        return {name}.From(PalUlid.Parse(reader.GetString() ?? throw new JsonException(\"Ulid identity JSON value cannot be null.\"), CultureInfo.InvariantCulture));",
        "int" => $"        return {name}.From(reader.GetInt32());",
        "long" => $"        return {name}.From(reader.GetInt64());",
        "string" => $"        return {name}.From(reader.GetString() ?? throw new JsonException(\"String identity JSON value cannot be null.\"));",
        _ => "        throw new JsonException(\"Unsupported identity source type.\");"
    };

    private static string JsonWriteBody(string srcType) => srcType switch
    {
        "Guid" => "        writer.WriteStringValue(value.Value);",
        "Ulid" => "        writer.WriteStringValue(value.Value.ToString());",
        "int" => "        writer.WriteNumberValue(value.Value);",
        "long" => "        writer.WriteNumberValue(value.Value);",
        "string" => "        writer.WriteStringValue(value.Value);",
        _ => "        throw new JsonException(\"Unsupported identity source type.\");"
    };

    private static string NumericOperators(string name, string srcType) => $$"""

    public static {{name}} operator ++({{name}} value) => new() { Value = ({{srcType}})(value.Value + 1) };
    public static {{name}} operator --({{name}} value) => new() { Value = ({{srcType}})(value.Value - 1) };
""";

    private sealed record IdGenInfo(string Namespace, string TypeName, string SourceType, bool IsNumeric);
}
